package: yform_spam_protection
version: '1.0.5-dev'
author: 'Alexander Walther, FriendsOfREDAXO'
supportpage: https://github.com/friendsofredaxo/yform_spam_protection

requires:
    redaxo: ^5.9
    yform: '>=3,<4'
    php:
        version: ^7.1

page:
    hidden: true

pages:
    yform/spam_protection:
        title: 'Spamschutz'
        subpages:
            settings:
                title: 'Einstellungen'
            docs:
                title: 'Dokumentation'
            
default_config:
    timer: 5
